Repository Tastypotato245/OOP_Project02, pull requests merged in 2023-11, with the labels that each got.

#2 feat/multiple-argument 기능 추가
  .gitignore
  Makefile
  calculator.cpp
  calculator.h
  main.cpp
Labels: enhancement

#3 일부 한글 주석들을 영어로 바꿨습니다.
  README.md
  calculator.cpp
  calculator.h
  inf_int.cpp
  inf_int_null.cpp
  main.cpp
Labels: documentation

#6 fix: 0이 들어왔을 때 종료하도록 하였습니다.
  main.cpp
Labels: bug

#7 에러 수정 : 범위 힙 메모리 넘어가는 문제 수정하였습니다
  inf_int.cpp
  inf_int_null.cpp
Labels: bug

#8 +, - 버그 수정
  .gitignore
  Makefile
  calculator.cpp
  inf_int.cpp
  inf_int.h
Labels: bug

#10 최종
  Makefile
  calculator.cpp
  calculator.h
  inf_int_null.cpp
  main.cpp
Labels: bug
